---
:Platform:
- &1
  :args:
    :x: 0
    :y: 0
    :h: 1
    :w: MAX_W
    :color: :green
- &1
  :args:
    :x: 0
    :y: MAX_Y
    :h: 1
    :w: MAX_W
    :color: :blue
- &1
  :args:
    :x: 0
    :y: 0
    :h: MAX_H
    :w: 1
    :color: :blue
- &1
  :args:
    :x: MAX_X
    :y: 0
    :h: MAX_H
    :w: 1
    :color: :blue
