---
:Environment::MapMeta:
- :args:
    :Song:
      :filename: test8bit3.wav
:Environment::Platform:
- :args:
    :x: 0
    :y: 0
    :h: 1
    :w: 20
    :color: :green
- :args:
    :x: 0
    :y: 14
    :h: 2
    :w: 20
    :color: :blue
- :args:
    :x: 0
    :y: 0
    :h: 15
    :w: 1
    :color: :blue
- :args:
    :x: 19
    :y: 0
    :h: 15
    :w: 1
    :color: :blue
- :args:
    :x: 7
    :y: 11
    :h: 1
    :w: 10
    :color: :blue
- :args:
    :x: 9
    :y: 8
    :h: 1
    :w: 4
    :color: :blue
- :args:
    :x: 11
    :y: 5
    :h: 1
    :w: 4
    :color: :blue
:Entities::Townsfolk:
- :args:
    :start_x: 10
    :start_y: 2
    :actions: ['move', 'jump']
- :args:
    :start_x: 9
    :start_y: 2
    :actions: ['move', 'jump']
- :args:
    :start_x: 8
    :start_y: 2
- :args:
    :start_x: 7
    :start_y: 2
