---
:platform:
- &1
  :args:
    :x: 0
    :y: 0
    :h: 1
    :w: MAX_W
    :color: :green
- &1
  :args:
    :x: 0
    :y: :max
    :h: 1
    :w: MAX_W
    :color: :blue
- &1
  :args:
    :x: 0
    :y: 0
    :h: MAX_H
    :w: :1
    :color: :blue
- &1
  :args:
    :x: 0
    :y: 0
    :h: MAX_H
    :w: 1
    :color: :blue
